# Generated by Django 2.2.11 on 2020-04-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deferred_save', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(to='deferred_save.Tag'),
        ),
    ]
