# Generated by Django 2.2.11 on 2020-04-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deferred_save', '0002_auto_20200401_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deferred_save.Comment'),
        ),
    ]
